//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.30 at 03:21:55 PM MDT 
//


package co.com.foundation.javeriana.sandbox.model.output;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.swa.sandbox.model.output package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.swa.sandbox.model.output
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FlightLegResponse }
     * 
     */
    public FlightLegResponse createFlightLegResponse() {
        return new FlightLegResponse();
    }

    /**
     * Create an instance of {@link FlightLegResponse.FlightLeg }
     * 
     */
    public FlightLegResponse.FlightLeg createFlightLegResponseFlightLeg() {
        return new FlightLegResponse.FlightLeg();
    }

    /**
     * Create an instance of {@link FlightLegResponse.FlightLeg.Usages }
     * 
     */
    public FlightLegResponse.FlightLeg.Usages createFlightLegResponseFlightLegUsages() {
        return new FlightLegResponse.FlightLeg.Usages();
    }

    /**
     * Create an instance of {@link FlightLegResponse.FlightLeg.FlightAttributes }
     * 
     */
    public FlightLegResponse.FlightLeg.FlightAttributes createFlightLegResponseFlightLegFlightAttributes() {
        return new FlightLegResponse.FlightLeg.FlightAttributes();
    }

    /**
     * Create an instance of {@link FlightLegResponse.FlightLeg.Aircraft }
     * 
     */
    public FlightLegResponse.FlightLeg.Aircraft createFlightLegResponseFlightLegAircraft() {
        return new FlightLegResponse.FlightLeg.Aircraft();
    }

    /**
     * Create an instance of {@link FlightLegResponse.FlightLeg.Airports }
     * 
     */
    public FlightLegResponse.FlightLeg.Airports createFlightLegResponseFlightLegAirports() {
        return new FlightLegResponse.FlightLeg.Airports();
    }

    /**
     * Create an instance of {@link FlightLegResponse.FlightLeg.Dates }
     * 
     */
    public FlightLegResponse.FlightLeg.Dates createFlightLegResponseFlightLegDates() {
        return new FlightLegResponse.FlightLeg.Dates();
    }

    /**
     * Create an instance of {@link FlightLegResponse.FlightLeg.Usages.Usage }
     * 
     */
    public FlightLegResponse.FlightLeg.Usages.Usage createFlightLegResponseFlightLegUsagesUsage() {
        return new FlightLegResponse.FlightLeg.Usages.Usage();
    }

}
