//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.30 at 03:21:41 PM MDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://xml.mxi.com/xsd/aes/javeriana/flight/flight-leg-request/1.0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package co.com.foundation.javeriana.sandbox.model.input;
